name: hjulfix_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #* State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #* API Network Calling
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1

  #* Logging
  logging: ^1.3.0

  #* Response Handling
  fpdart: ^1.1.1

  #* Network Connectivity
  connectivity_plus: ^6.1.4

  #* Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_multiple_loaders: ^1.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  go_router: ^15.2.3
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.4

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/native_splash/welcome-icon.png
  branding: assets/native_splash/brand.png
  branding_bottom_padding_ios: 35

#  color_dark: "#332828"
  android_12:
    color: "#ffffff"
#    color_dark: "#332828"
    image: assets/native_splash/welcome.png
    branding: assets/native_splash/brand.png
#    branding: assets/native_splash/branding-new.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/native_splash/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700