name: hjulfix_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #* State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  #* API Network Calling
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1

  #* Logging
  logging: ^1.3.0

  #* Response Handling
  fpdart: ^1.1.1

  #* Network Connectivity
  connectivity_plus: ^6.1.4

  #* Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700